#!/usr/bin/env python

import sys
import re

import util
from lattice import Lattice2D

#Measurement properties
EQUILIBRIATION_SWEEPS = 500
MEASUREMENT_SWEEPS = 500
SAMPLING_FREQUENCY = 1

#Temperature dependence measurements
STARTING_TEMPERATURE = 1.0
FINAL_TEMPERATURE = 5
TEMPERATURE_STEP = 0.1

class Ising2D:

    _lattice = None

    def __init__(self, lattice_size, magnetic_field, preruns=False):
        """Set up the model and calculate temperature dependencies of
        equilibrium properties."""

        if preruns:
            self.prerun(lattice_size, magnetic_field, preruns)
        else:
            self.calculate_temperature_dependence(lattice_size, magnetic_field)

    def prerun(self, lattice_size, magnetic_field, preruns):
        """Generate equilibriation data to determine equilibriation time
        for set lattice size."""

        for i in range(preruns):
            print("Running equilibriation {2} for run {0}x{0}-B{1}".format(
                lattice_size,
                magnetic_field,
                i+1))
            #Runs are are identified by lattice size and magnetic field
            #E.g. 10x10-B0.5
            self._run_id = "{0}x{0}-B{1}-prerun{2}".format(
                lattice_size,
                magnetic_field,
                i+1)

            #Initialize new lattice
            self._lattice = Lattice2D(lattice_size,
                T=STARTING_TEMPERATURE,
                B=magnetic_field,
                prerun=True)

            self.equilibriate(2000, prerun=True)

    def calculate_temperature_dependence(self, lattice_size, magnetic_field):
        """Calculate temperature dependence of the magnetization, energy,
        heat capacity and magnetic susceptibility."""

        #Runs are are identified by lattice size and magnetic field
        #E.g. 10x10-B0.5
        self._run_id = "{0}x{0}-B{1}".format(lattice_size, magnetic_field)

        #Initialize new lattice
        self._lattice = Lattice2D(lattice_size,
                                 T=STARTING_TEMPERATURE,
                                 B=magnetic_field)

        #Start measuring averages at increasing temperatures
        results = {}

        print("Calculating temperature dependence...")
        while self._lattice.T < FINAL_TEMPERATURE:
            print("T: {0}".format(self._lattice.T))

            #Equilibriate lattice after each temperature increase
            self.equilibriate(EQUILIBRIATION_SWEEPS)

            #Sample equilibrium properties
            data = self.sample()

            #Store raw data for post-processing
            util.write_raw_data(data, self._run_id, self._lattice.T)

            #Calculate averages and response functions
            results[self._lattice.T] = self.calculate_properties(data)

            #Increase temperature for next measurement cycle
            self._lattice.set_temperature(self._lattice.T + TEMPERATURE_STEP)

        #Write results to disk
        util.write_results(results, self._run_id)

        #Find critical temperature from response functions
        Xtmax = 0
        Xbmax = 0
        Tc = {"M" : 0, "E" : 0}
        for temperature in results:
            Xt = (results[temperature]["E2"] - results[temperature]["E"]**2) / float(temperature)**2
            Xb = (results[temperature]["M2"] - results[temperature]["M"]**2) / float(temperature)
            if Xt > Xtmax:
                Tc["E"] = temperature
                Xtmax = Xt
            if Xb > Xbmax:
                Tc["M"] = temperature
                Xbmax = Xb

        util.store_critical_temperature(Tc, self._run_id)

        print("""Critical temperature for {0}
            Based on energy fluctuations: {1}
            Based on fluctuations in magnetization: {2}
            Average: {3}""".format(self._run_id, Tc["E"], Tc["M"], (Tc["E"] + Tc["M"]) / 2.0))

    def equilibriate(self, cycles, prerun=False):
        """Equlilibriate the lattice before sampling."""

        #Step counter
        n = 0

        #Equilibriation log
        log = [("x", "y",)]

        b = 0
        for sweep in range(cycles):
            for i in range(self._lattice.length**2):
                #Perform MC step
                self._lattice.mc_move()
                n += 1
                if i % (1 + self._lattice.length**2 / 100) == 0:
                    b += 1
                    #Log magnetization to track equilibriation progress
                    if prerun:
                        magnetization = str(abs(self._lattice.get_magnetization()))
                    else:
                        magnetization = str(self._lattice.get_magnetization())
                    log.append((str(n/float(self._lattice.length**2)),
                        magnetization,))

        #Write equilibriation log to disk
        util.write_log(log,
            self._run_id,
            "equilibriation-T{0}.csv".format(self._lattice.T))

    def calculate_properties(self, data):
        """Calculate properties from sampled data."""

        #Calculate averages of the energy and it's square
        E = 0.0
        E2 = 0.0
        for e in data["E"]:
            E += e
            E2 += e**2
        E = E / len(data["E"])
        E2 = E2 / len(data["E"])

        #Calculate averages of the magnetization and it's square
        M = 0.0
        M2 = 0.0
        for m in data["M"]:
            M += m
            M2 += m**2
        M = M / len(data["M"])
        M2 = M2 / len(data["M"])

        return {"E" : E, "E2" : E2, "M" : M, "M2" : M2}

    def sample(self):
        """Sample equilibrium properties from current configuration."""

        data = {"E" : [], "M" : []}

        for n in range(MEASUREMENT_SWEEPS * self._lattice.length**2):
            self._lattice.mc_move()
            if n % SAMPLING_FREQUENCY == 0:
                magnetization = self._lattice.get_magnetization()
                energy = self._lattice.get_energy()
                data["M"].append(magnetization)
                data["E"].append(energy)
        return data

if __name__ == "__main__":
    preruns = False
    for arg in sys.argv:
        normal_match = re.search('(\d+)x(\d+)-B([-+]?[0-9]*\.?[0-9]+)', arg)
        if normal_match:
            lattice_size = int(normal_match.group(1))
            magnetic_field = float(normal_match.group(3))
        prerun_match = re.search('-pre(\d)', arg)
        if prerun_match:
            preruns = int(prerun_match.group(1))
    if not "+r" in sys.argv:
        if preruns:
            Ising2D(lattice_size, magnetic_field, preruns)
        else:
            Ising2D(lattice_size, magnetic_field, preruns)
    if not "-r" in sys.argv:
        #Generate a PDF report of the results
        if preruns:
            util.generate_prerun_report("{0}x{0}-B{1}".format(lattice_size,
            magnetic_field))
        else:
            util.generate_report("{0}x{0}-B{1}".format(lattice_size,
            magnetic_field))
